config-examples/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    
    # All URI redirection occurs at /uri-gin/ URLs
    url(r'^uri-gin/', include('uriredirect.urls')),
    
    # All validation occurs at /validate/ URLs
    url(r'^validate/', include('modelmanager.validation.urls')),
)

# Append urlpatterns from modelmanager.contentmodels
from modelmanager.urls import urlpatterns as cm_urls
urlpatterns += cm_urls

urls.py
from django.conf.urls import patterns, url
from django.conf import settings

urlpatterns = patterns('modelmanager.views',

                       # Get all the ContentModels as JSON or HTML
                       url(r'^contentmodels\.(?P<extension>json|html|xml|drupal)$', 'get_all_models'),

                       # Get a single ContentModel as JSON or HTML
                       url(r'^contentmodel/(?P<content_model>.*)\.(?P<extension>json|html|xml|drupal)$', 'get_model'),

                       # Get a FeatureCatalogue for a particular ModelVersion
                       url(r'^featurecatalog/(?P<content_model>.*)/(?P<model_version>.*)\.xml', 'get_feature_catalog'),

                       # Homepage
                       url(r'^home/$', 'homepage'),

                       # Model viewing page
                       url(r'^models/$', 'models'),

                       # Tools page
                       url(r'^tools/$', 'tools'),

                       # Swagger documentation
                       url(r'^docs/', 'swaggerui'),
                       url(r'^swagger/(?P<path>.*)', 'swagger')
)

# Serve static files
if settings.DEBUG:
    urlpatterns += patterns('',
                            url(r'^files/(?P<path>.*)$', 'django.views.static.serve',
                                {'document_root': settings.MEDIA_ROOT}),
    )

validation/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('modelmanager.validation.validators',

  # Validation form, and form submission
  url('^wfs$', 'validate_wfs_form'),
  url('^cm$', 'validate_cm_form'),
  url('^dl_csv$', 'download_csv')
)

models.py
from django.db import models
from django.conf import settings
from django.template.defaultfilters import slugify
from django.db.models.signals import pre_save, post_save, post_delete
#from django.dispatch import receiver
from uriconfigure import adjust_rewrite_rule, delete_rewrite_rule, update_related_rewrite_rules, RewriteRule
from os import path
from lxml import etree
from overwriter import Overwriter
import re
from collections import OrderedDict

#--------------------------------------------------------------------------------------
# Function that gets the path for a uploaded files.
#     File path will be content-model-slug/version-number/filename            
#--------------------------------------------------------------------------------------
def get_file_path(instance, filename):
    return '%s/%s/%s' % (instance.content_model.folder_path(), instance.version, filename)
    
#--------------------------------------------------------------------------------------
# Function that strips HTML tags (except anchors) from strings         
#--------------------------------------------------------------------------------------
def removeTags(string_to_clean):
    cleaned = re.sub('</(?!a)[^>]*>|<[^/a][^>]*>', '', string_to_clean)
    return re.sub('&nbsp;', ' ', cleaned)

def add_target_to_anchors(string_to_fix, target="_blank"):
    """Given arbitrary string, find <a> tags and add target attributes"""
    pattern = re.compile("<a(?P<attributes>.*?)>")
    
    def repl_func(matchobj):
        pattern = re.compile("target=['\"].+?['\"]")
        attributes = matchobj.group("attributes")
        if pattern.search(attributes):
            return "<a%s>" % re.sub(pattern, "target='%s'" % target, attributes)
        else:
            return "<a%s target='%s'>" % (attributes, target)
    
    return re.sub(pattern, repl_func, string_to_fix)    
 
#--------------------------------------------------------------------------------------
# This class represent specific USGIN content-models, which are built to convey
#     specific types of geoscience information.
#--------------------------------------------------------------------------------------
class ContentModel(models.Model):
    class Meta:
        ordering = ['title']    # Defines the order of any list of ContentModels
        
    # Define the class data members
    title = models.CharField(max_length=2500)
    label = models.CharField(max_length=2500, unique=True)
    description = models.TextField()
    discussion = models.TextField(blank=True)
    status = models.TextField(blank=True)
    rewrite_rule = models.OneToOneField(RewriteRule, null=True, blank=True)
    
    # Functions to return cleaned-up properties
    def cleaned_description(self):
        return removeTags(self.description)
        
    def cleaned_discussion(self):
        return removeTags(self.discussion)
        
    def cleaned_status(self):
        return removeTags(self.status)
    
    # Define the "display name" for an instance
    def __unicode__(self):
        return self.title
    
    # Define the folder path for an instance -- just a simplification of the title
    def folder_path(self):
        return slugify(self.title)
    
    # Simple pointer to the latest version of a instance
    def latest_version(self):
        if self.modelversion_set.count() > 0: return self.modelversion_set.latest('date_created')
        else: return None
    
    # Simply return the latest version number
    def latest_version_number(self):
        version = self.latest_version()
        if version: return version.version
        else: return None
    
    # The updated date for an instance is the last time that a version was created
    def date_updated(self):
        version = self.latest_version()
        if version is not None: return version.date_created
        else: return None
        
    # Return the updated date as an ISO-formatted string
    def iso_date_updated(self):
        updated = self.date_updated()
        if updated is not None: return updated.isoformat()
        else: return None
    
    # Return the absolute path to the latest version's XSD file
    def absolute_latest_xsd_path(self):
        version = self.latest_version()
        if version is not None: return self.latest_version().absolute_xsd_path()
        else: return None
    
    # Return the absolute path to the latest version's XLS file
    def absolute_latest_xls_path(self):
        version = self.latest_version()
        if version is not None: return self.latest_version().absolute_xls_path()
        else: return None
    
    # Provide a link to the latest version's XSD file
    def latest_xsd_link(self):
        version = self.latest_version()
        if version != None: return self.latest_version().xsd_link()
        else: return None
    latest_xsd_link.allow_tags = True
    
    # Provide a link to the latest version's XLS file
    def latest_xls_link(self):
        version = self.latest_version()
        if version != None: return self.latest_version().xls_link()
        else: return None
    latest_xls_link.allow_tags = True
    
    # Construct the link for the nice-looking HTML for a particular model
    def my_pretty_html(self):
        return "%s/models/#%s" % (settings.BASE_URL.rstrip("/"), self.label)
    
    # Provide a URL for this ContentModel as HTML. Needs to be in sync with urls.py.
    def my_html(self):
        return '%s/contentmodel/%s.html' % (settings.BASE_URL.rstrip('/'), self.pk)
    
    # Provide a URL for this ContentModel as JSON. Needs to be in sync with urls.py.
    def my_json(self):
        return '%s/contentmodel/%s.json' % (settings.BASE_URL.rstrip('/'), self.pk)
    
    # Provide a URL for this ContentModel as Atom XML. Needs to be in sync with urls.py.
    def my_atom(self):
        return '%s/contentmodel/%s.xml' % (settings.BASE_URL.rstrip('/'), self.pk)
        
    # Return RegEx pattern for use in UriRegister module
    def stripped_regex(self):
        return "xmlschema/%s/" % self.label
    
    def regex_pattern(self):
        return '^%s(\.[a-zA-Z]{3,4}|/)?$' % self.stripped_regex()
    
    # Provide this ContentModel's relative URI
    def relative_uri(self):
        return '/uri-gin/%s/%s' % (settings.URI_REGISTER_LABEL, self.stripped_regex())
    
    # Provide this ContentModel's absolute URI
    def absolute_uri(self):
        return '%s%s' % (settings.SCHEMA_URI.rstrip('/'), self.relative_uri())
    
    # Return a link to this ContentModel's RewriteRule
    def rewrite_rule_link(self):
        return '<a href="/admin/uriredirect/rewriterule/%s">Edit Rule</a>' % self.rewrite_rule.pk
    rewrite_rule_link.allow_tags = True
    
    # Return a discussion text where <a> tags have been given target="_blank" attributes
    def discussion_for_drupal(self):
        return add_target_to_anchors(self.cleaned_discussion())
    
    # Return status text where <a> tags have been given target="_blank" attributes
    def status_for_drupal(self):
        return add_target_to_anchors(self.cleaned_status())
    
    # Return description text where <a> tags have been given target="_blank" attributes
    def description_for_drupal(self):
        return add_target_to_anchors(self.cleaned_description())
    
    # Return the most recent three versions, most recent first
    def recent_versions(self):
        return self.modelversion_set.order_by("-date_created")[:3]
    
    # Return the instance as a dictionary that can be easily converted to JSON
    #     Include a list of versions relevant to this content model
    def serialized(self):
        as_json = {
            'title': self.title,
            'uri': self.absolute_uri(),
            'label': self.label,
            'description': self.description,
            'discussion': self.discussion,
            'status': self.status,
            'date_updated': self.iso_date_updated(),
            'versions': [ mv.serialized() for mv in self.modelversion_set.all() ]
        }        
        return as_json

    # Return the layer name that should be used for this model
    def layer_name(self):
        return self.latest_version().type_details().layername

#--------------------------------------------------------------------------------------
# This class represents a specific version of a particular content-model. 
#     A one-to-many relationship exists between ContentModels and ModelVersions. 
#--------------------------------------------------------------------------------------
class ModelVersion(models.Model):
    class Meta:
        ordering = ['version']    # Defines the order of any list of ModelVersions
        
    # Define the models data members
    content_model = models.ForeignKey('ContentModel')
    version = models.CharField(max_length=10)
    date_created = models.DateField(auto_now_add=True)
    xsd_file = models.FileField(upload_to=get_file_path, storage=Overwriter())
    xls_file = models.FileField(upload_to=get_file_path, storage=Overwriter())
    sld_file = models.FileField(upload_to=get_file_path, storage=Overwriter(), blank=True)
    lyr_file = models.FileField(upload_to=get_file_path, storage=Overwriter(), blank=True)
    sample_wfs_request = models.CharField(max_length=2000, blank=True)
    rewrite_rule = models.OneToOneField(RewriteRule, null=True, blank=True)

    # Return the first-decimal, or "Major" version number. In the case of version 1.23 this would be 1.2
    def major_version(self):
        m = re.match('\d*\.\d{1}', self.version)
        if m: return m.group(0)
        else: return None
    
    # Define the "display name" for an instance
    def __unicode__(self):
        return '%s v. %s' % (self.content_model.title, self.version)
    
    # Define the absolute URI for this version -- it is simply the version number appended to the ContentModel.uri    
    def absolute_uri(self):
        return '%s/%s' % (self.content_model.absolute_uri().rstrip('/'), self.version)
    

templates/validation/cm-form-bootstrap.html
{% extends "base.html" %}

{% block title %}CM Validator{% endblock %}

{% block navhome %}{% endblock %}
{% block navcmvalidator %}class="active"{% endblock %}

{% block scripts %}
<script type="text/javascript" src="/static/validation/js/modelversions.js"></script>
{% endblock %}

{% block content %}
<div class="row">
  <div class="span10 offset1">
    <legend><h1>Validate & Fix CSV Data in a USGIN Model</h1></legend>
    <div>
      <form action="/validate/cm" name="csv-upload" method="post" enctype="multipart/form-data" > {% csrf_token %}
    	<div class="control-group">
          {{ form.content_model.errors }}
          <label for="id_content_model" class="control-label">Content Model:</label>
          <div class="controls">
            {{ form.content_model }}
          </div>
    	</div>
        <div class="control-group">
          {{ form.version.errors }}
          <label for="id_version" class="control-label">Version:</label>
            <div class="controls">
              {{ form.version }}
            </div>
    	  </div>
    	<div class="control-group">
          {{ form.feature_type.errors }}
          <label for="id_feature_type" class="control-label">Feature Type:</label>
          <div class="controls">
            {{ form.feature_type }}
          </div>
    	</div>
        <br>
        <div class="control-group">
          {{ form.file.errors }}
          <label for="id_upload_file" class="control-label">Select CSV file to validate:</label>

        <p class="text-error"><em><small> Currently only files about 15MB or less (~25000 rows) can be processed. Larger files can still be processed if they are broken up. </small></em></p>
            <div class="controls">
              {{form.file}}
            </div>
        </div>
        <br>
        <input type="submit" value="Validate!" class="btn btn-success">
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/validation/cm-results-bootstrap.html
{% extends "base.html" %}

{% block title %}CM Validator{% endblock %}

{% block navhome %}{% endblock %}
{% block navcmvalidator %}class="active"{% endblock %}

{% block content %}
<div class="row">
  <div class="span12">
    <div class="alert alert-{%if valid %}success{% else %}error{% endif %}">
      <h3> {% if valid and not messages %}
             PASSED VALIDATION
           {% elif valid and messages %}
             VALID WITH THE CHANGES BELOW
           {% else %}
             FAILED VALIDATION
           {% endif %}</h3>
    </div>
    <hr>
    <p> File selected: {{ filepath }} </p>
  {% if not dataCorrected %}
    <p class="text-error"> {{ messages }} </p>
  {% else %}
    {% if messages %}
       <p class="text-error"> File does not conform to the selected content model.
       {% if valid %} However, if the changes indicated below are acceptable, download the file below for a conforming copy of your data.</p>
       {% else %} <p> The issues indicated in the error messages below must be made before the data will validate. If the changes indicated in the Warning and Notice messages are acceptable, download the file below and then in that document fix the indicated errors.</p>
        {% endif %}

  	<ul class="unstyled">
     <legend>Messages from the Validator</legend>
    <p class="muted"> <em><small> Note that in the messages below Row 0 indicates the header row.<br>If your CSV viewer indicates the header row as Row 1 the row numbers below will need to be incremented by 1.</small></em></p>
  	  {% for message in messages %}
        <li>
          {% if "Error!" in message %}
  		    <span class="label label-important">*</span>
  		    <span class="text-error">
          {% elif "Warning!" in message %}
            <span class="text-warning">
          {%  elif "Notice!" in message %}
             <span class="text-info">
          {% else %}
             <span class="text-muted">
          {% endif %}{{ message }}</span>
  		</li>
  	  {% endfor %}
  	</ul>
  	<hr>
   <form action="/validate/dl_csv" name="csv-download" method="post">
       {% csrf_token %}
       <legend>Download</legend>
       <p> Click the button below to download a copy of your data which has applied to it the changes indicated in the Warning and Notice messages. </p>
   <button type="submit" name="new_data" value="{{ dataCorrected }}">Download!</button>
   </form>
  {% else %}
      <p class="text-success"> File conforms to the selected content model.</p>
  {% endif %}
  {% endif %}
  </div>
</div>
{% endblock %}

templates/validation/wfs-form-bootstrap.html
{% extends "base.html" %}

{% block title %}WFS Validator{% endblock %}

{% block navhome %}{% endblock %}
{% block navvalidator %}class="active"{% endblock %}

{% block scripts %}
<script type="text/javascript" src="/static/validation/js/modelversions.js"></script>
{% endblock %}

{% block content %}
<div class="row">
  <div class="span10 offset1">    
    <form action="/validate/wfs" method="post" {% if url %}class="form-horizontal"{% endif %}>{% csrf_token %}
      <legend><h1>Validate a WFS GetFeature Request</h1></legend>
      {{ form.non_field_errors }}
      <div>
        {{ form.wfs_get_capabilities_url.errors }}
        {{ form.wfs_get_capabilities_url }}
      </div>
      {% if url %}
      <div class="control-group">
        <span class="span10 uneditable-input">{{ url }}</span>
      </div>
    	{{ form.url }}
    	<div class="control-group">
        {{ form.feature_type.errors }}
        <label for="id_feature_type" class="control-label">FeatureType:</label>
        <div class="controls">
          {{ form.feature_type }}
        </div>
    	</div>
    	<div class="control-group">
        {{ form.number_of_features.errors }}
        <label for="number_of_features" class="control-label">Number of Features:</label>
        <div class="controls">
          {{ form.number_of_features }}
        </div>
    	</div>
    	<legend>Choose the Model and Version to Validate Against</legend>
    	<div class="control-group">
        {{ form.content_model.errors }}
        <label for="id_content_model" class="control-label">Content Model:</label>
        <div class="controls">
          {{ form.content_model }}
        </div>
    	</div>
    	<div class="control-group">
        {{ form.version.errors }}
        <label for="id_version" class="control-label">Version:</label>
        <div class="controls">
          {{ form.version }}
        </div>
    	</div>
    	{% endif %}
      <input type="submit" value="Submit" class="btn btn-success">
    </form>
  </div>
</div>
{% endblock %}

templates/validation/wfs-form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>WFS Validator</title>
  </head>
  <body>
  	{% if url %}
  	<p><a href="{{ url }}">{{ url }}</a></p>
  	{% endif %}
    <form action="/validate/wfs" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
    </form>
  </body>
</html>

templates/validation/wfs-result.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>WFS Validator</title>
  </head>
  <body>
  	<h2>The following WFS GetFeature Request was made:</h2>
  	<div>
  		<dl>
  			<dt>Base URL: </dt>
  			<dd>{{ wfs_base_url }}</dd>
  			
  			<dt>Feature Types: </dt>
  			<dd>{{ feature_type }}</dd>
  			
  			<dt>Number of Features: </dt>
  			<dd>{{ number_of_features }}</dd>
  			
  			<dt>Link to GetFeature Response: </dt>
  			<dd><a href="{{ url }}">GetFeature Document</a></dd>
  		</dl>
  	</div>
  	<h2>The response was validated against the following Content Model:</h2>
  	<div>
  		<dl>
  			<dt>Model Name: </dt>
  			<dd>{{ modelversion.content_model.title }}</dd>
  			
  			<dt>Model Version: </dt>
  			<dd>{{ modelversion.version }}</dd>
  			
  			<dt>Link to XSD Document: </dt>
  			<dd><a href="{{ modelversion.absolute_xsd_path }}">{{ modelversion.xsd_filename }}</a></dd>
  		</dl>
  	</div>
  	<h2>The response <strong>{% if valid %}PASSED{% else %}FAILED{% endif %}</strong> validation.</h2>
  	<p>The wfs:FeatureCollection contained {{ valid_elements }} valid {{ feature_type }} elements</p>
  	{% if errors %}
  	<ul>
  		{% for error in errors %}
  		<li>{{ error.message }}</li>
  		{% endfor %}
  	</ul>
  	{% endif %}
  </body>
</html>

templates/validation/wfs-results-bootstrap.html
{% extends "base.html" %}

{% block title %}WFS Validator{% endblock %}

{% block navhome %}{% endblock %}
{% block navvalidator %}class="active"{% endblock %}

{% block content %}
<div class="row">
  <div class="span12">
    <div class="alert alert-{%if valid %}success{% else %}error{% endif %}">
      <h3>{% if valid %}PASSED{% else %}FAILED{% endif %} VALIDATION</h3>
    </div>
    <hr>
    {% if errors %}
  	<ul class="unstyled">
  		{% for error in errors %}
  		<li>
  		  <span class="label label-important">Error</span>
  		  <span class="text-error">{{ error }}</span>
  		</li>
  		{% endfor %}
  	</ul>
  	<hr>
  	{% endif %}
  	<p><i class="icon-chevron-right"></i>  Here is the <a href="{{ url }}">WFS Response that you validated.</a></p>
  	<p><i class="icon-chevron-right"></i>  Here is <a href="{{ modelversion.absolute_xsd_path }}">the schema document that was used to validate it.</a></p>
  	<p><i class="icon-chevron-right"></i>  That schema document represents version {{ modelversion.version }} of the <a href="/models/#{{ modelversion.content_model.label }}">{{ modelversion.content_model.title }} content model</a>.</p>
  	<p class="text-{% if valid_elements != 0 %}success{% else %}error{% endif %}"><i class="icon-chevron-right"></i>  There {% if valid_elements > 1 %}were{% else %}was{% endif %} {{ valid_elements }} valid {{ feature_type }} element{% if valid_elements > 1 %}s{% endif %} in the response.</p>
    {% if not valid %}
    <p class="text-error"><i class="icon-chevron-right"></i>  There {% if invalid_elements > 1 %}were{% else %}was{% endif %} {{ invalid_elements }} invalid {{ feature_type }} element{% if invalid_elements > 1 %}s{% endif %} in the response.</p>
    <div class="accordion" id="error-accordion">
        {% for bad in invalid_results %}
        <div class="accordion-group">
            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#error-accordion" href="#error-{{ forloop.counter }}">
                    Bad Record # {{ forloop.counter }}
                </a>
            </div>
            <div id="error-{{ forloop.counter }}" class="accordion-body collapse">
                <div class="accordion-inner">
                    <pre class="prettyprint">{{ bad }}</pre>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

{%  block scripts %}
<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>
{% endblock %}